# Generated by Django 2.2.12 on 2020-07-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPath',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('song_path', models.CharField(max_length=255, verbose_name='url')),
                ('song_pic_path', models.CharField(max_length=45, verbose_name='图片路劲')),
            ],
            options={
                'db_table': 'song_song_path',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='歌曲名称')),
                ('ctr', models.IntegerField(default=0, verbose_name='点击量')),
                ('lyric_id', models.IntegerField(null=True, unique=True, verbose_name='歌词id')),
                ('album_id', models.IntegerField(null=True, verbose_name='专辑id')),
                ('label_set', models.IntegerField(default=0, verbose_name='标签')),
                ('is_active', models.BooleanField(default=0, verbose_name='授权')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.Singer')),
            ],
            options={
                'verbose_name_plural': '曲库',
                'db_table': 'song_song',
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_lyric', models.TextField(default='', verbose_name='歌词')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, verbose_name='专辑名')),
                ('album_pic_path', models.CharField(max_length=45, verbose_name='专辑封面')),
                ('is_active', models.BooleanField(default=0, verbose_name='授权')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.Singer')),
            ],
            options={
                'db_table': 'song_album',
            },
        ),
    ]
