# Generated by Django 2.2.12 on 2020-07-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('lable_set', models.CharField(max_length=50, null=True, verbose_name='标签')),
                ('area', models.CharField(choices=[('0', '中国'), ('1', '欧美'), ('2', '日韩'), ('3', '其他')], default='0', max_length=2, verbose_name='地区')),
                ('is_team', models.BooleanField(default=False, verbose_name='乐队')),
                ('introduce', models.CharField(default='', max_length=150, null=True, verbose_name='简介')),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='SingerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('country', models.CharField(max_length=30, verbose_name='国籍')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女'), ('2', '保密')], max_length=2, verbose_name='性别')),
                ('age', models.CharField(max_length=8, null=True, verbose_name='年龄')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像')),
                ('info', models.CharField(default='', max_length=255, null=True, verbose_name='歌手介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.Singer')),
            ],
            options={
                'db_table': 'singer_info',
            },
        ),
    ]
