# Generated by Django 2.2.12 on 2020-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='introduce',
            field=models.CharField(blank=True, max_length=150, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='lable_set',
            field=models.CharField(blank=True, max_length=50, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='singerinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='singerinfo',
            name='info',
            field=models.CharField(blank=True, max_length=255, verbose_name='歌手介绍'),
        ),
    ]
